# Generated by Django 5.0.2 on 2024-02-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ir_lar_irlar_personir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('status', models.CharField(max_length=300)),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ir')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
    ]
